Repository ubsuny/CP1-24-HW5, pull requests merged in 2024-11, with the labels that each got.

#9 Create pull_request_template.md
  docs/pull_request_template.md
Labels: Organization

#10 Repo setup
  .devcontainer/python/devcontainer.json
  .github/workflows/pylinttest.yml
  requirements.txt
Labels: Organization

#11 Added comment about linting
  docs/pull_request_template.md
Labels: Organization

#27 Separating Pylint and Pytest
  .github/workflows/pylint.yml
  .github/workflows/pytest.yml
Labels: Organization

#12 fft / inverse fft
  fft_folder/preparation.py
  fft_folder/test_preparation.py
Labels: python

#35 Added get_timeseries to preparation.py and unit test to test_preparation.py
  fft_folder/__pycache__/preparation.cpython-311.pyc
  fft_folder/__pycache__/preparation.cpython-312.pyc
  fft_folder/__pycache__/test_preparation.cpython-312-pytest-8.3.3.pyc
  fft_folder/preparation.py
  fft_folder/test_preparation.py
Labels: enhancement, Data

#39 Moving Python Files to Clean up
  fft_folder/__pycache__/preparation.cpython-311.pyc
  fft_folder/__pycache__/preparation.cpython-312.pyc
  fft_folder/__pycache__/test_preparation.cpython-312-pytest-8.3.3.pyc
  preparation.py
  test_preparation.py
Labels: Organization

#33 CO2 Internation data compilation.
  CO2_International_Data/Africa_Data.txt
  CO2_International_Data/Antarctica_Data.txt
  CO2_International_Data/Asia_Data.txt
  CO2_International_Data/Balkan_Data.txt
  CO2_International_Data/Europa_Data.txt
  CO2_International_Data/NA_Data.txt
  CO2_International_Data/NOTES.txt
  CO2_International_Data/Oceania_Data.txt
  CO2_International_Data/SA_Data.txt
  CO2_International_Data/co2_international_data.json
  CO2_International_Data/international_data_converter.py
Labels: Data

#30 the complete fft inv fft and frequency finder
  preparation.py
  test_preparation.py
Labels: python, Algorithms/Math

#47 Methane Data NOTES.md File
  methane-data-collection/data/NOTES.md
Labels: documentation, Data

#60 updated fft mag
  preparation.py
Labels: python
